# Generated by Django 4.1.7 on 2023-03-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_traveloffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravelOffer',
        ),
    ]
