# Generated by Django 4.1.7 on 2023-03-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_tourguide_alter_recentpost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(choices=[('SOLO_TRAVELLER', 'Solo Traveller'), ('GROUP_OF_PEOPLE', 'Group of People'), ('GROUP_OF_ORGANSATION', 'Group of Organisation'), ('OTHERS', 'Others')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('budget', models.CharField(choices=[('BUDGET', 'Budget'), ('MID_RANGE', 'Mid-Range'), ('lUXURY', 'Luxury')], max_length=100)),
                ('query', models.TextField()),
            ],
        ),
    ]
